### ISSUE TITLE
base_config: re-init argpars

### ISSUE THREAD

**Issue by zombig** [zombig/zstlib#1]
If initiate Config Class instance with empty config path, it will init arpgars and ask the '--config' param. 

create test.py script for example

```python
from base_config import Config
cfg = Config()
print(cfg.__dict__)
```

and try to run it
```bash
python test.py 
usage: test.py [-h] --config CONFIG
test.py: error: argument --config is required
```

But after it you can't set any argparse params via config because argparse is already initiated and will failed.

For example: create config -- test.yaml
```yaml
test: value
argparse:
  description: test argparse via config
  arguments:
    second_test:
      help: simple test
      type: str
      required: yes
```
And provide it to our script
```bash
python test.py --config test.yaml 
usage: test.py [-h] --second_test SECOND_TEST
test.py: error: argument --second_test is required
```

But if we try to add missing param it will fail
```sh
python test.py --config test.yaml --second_test TEST
usage: test.py [-h] --config CONFIG
test.py: error: unrecognized arguments: --second_test TEST
```
